version: 2

before:
  hooks:
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
    - git push --tags

gomod:
  proxy: false

builds:
  - env: ["CGO_ENABLED=0"]
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags: ["-trimpath"]
    goos:
      - linux
      - darwin
    binary: sepa

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

release:
  github:
    owner: skatkov
    name: sepatui

brews:
  - homepage: "https://github.com/skatkov/sepatui"
    description: "A Terminal User Interface (TUI) application for viewing and analyzing SEPA XML payment files"
    name: sepa
    repository:
      owner: skatkov
      name: homebrew-tap
